sonar.projectKey=elidjeidevoper-startup_diario-ia
sonar.organization=elidjeidevoper-startup

# Caminho para o código fonte
sonar.sources=app
# Excluir pastas que não precisam de análise de qualidade
sonar.exclusions=node_modules/**, .next/**, out/**